version: "3"
services:
  nodejs-server:
    build:
      context: ./api
    ports:
      - "3080:3080"
    container_name: api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
       
  react-ui:
    build:
      context: ./my-app
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./my-app:/usr/src/app/my-app
       - ./data:/usr/src/app/data
       - /usr/src/app/my-app/node_modules

  selenium-chrome-standalone:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    container_name: selenium-chrome-standalone
    ports:
      - "4444:4444"
      - "7900:7900"

  selenium-test-search:
    image: search/selenium-61122
    depends_on:
      - selenium-chrome-standalone
      - react-ui
    container_name: search-test-selenium
    environment:
      - HUB_HOST=selenium-chrome-standalone
      - BROWSER=chrome
      - IP=172.20.0.2
      - MODULE=testng.xml
    volumes:
      - ./selenium-search-testing:/usr/src/app/selenium-search-testing
      - /usr/src/app/selenium-search-testing/Outputs
